services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: memora_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: spring-boot-memora
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/memora_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: "7f3c9a2e1d8b6f4a0c5e7d9b3a1f8c6e2d4b7a9f0c3e5d8b1a6f9c2e7d4b8a"
    ports:
      - "8080:8080"
    depends_on:
      - db